name: exif
version: 1.0.3
author: Taesu Pyo <pyotaesu@gmail.com>
description: Decode Exif data from tiff and jpeg files.
homepage: https://www.github.com/bigflood/dartexif
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  args: '>=^1.2.0'
  collection: '>=^1.0.0'
  convert: '>=^3.0.0'
  sprintf: '>=1.0.0 <5.0.0'
dev_dependencies:
  test:
  archive: '^2.0.2'
  path:
  http:
  json_annotation: ^1.0.0
  build_runner: ^0.10.0
  json_serializable: ^1.0.0
  stream_channel:
executables:
  print_exif:
  
